eobardthawne21p/Social-Connect

- features/step_definitions/social_connect_steps.rb
- features/support/save_post.feature
- features/support/sign-in.feature
- features/support/view_chat.feature
- features/support/view_maps.feature
- features/support/view_pop-up.feature
- features/support/view_saved_posts.feature
- features/support/view_settings_saved_posts.feature
- features/support/view_timeline.feature
Adding cucumber tests to setup branch - Paul
> Cucumber paul

- features/support/admin_add_moderator.feature
- features/support/admin_edit_moderators.feature
- features/support/approve_post.feature
- features/support/browse_moderator.feature
- features/support/decline_post
- features/support/delete_chat.feature
- features/support/delete_moderator.feature
- features/support/delete_user.feature
- features/support/report_moderator.feature
- features/support/report_user.feature
Added Cucumber tests to setup - Juan Carlos
> Add cucmber tests.

- Gemfile
- Gemfile.lock
- features/support/env.rb
Added the gem database_cleaner-mongoid for cucumber tests
> Added database cleaner

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/sessions/new.html.erb
- test/controllers/users_controller_test.rb
Login authentication, user is now able to login with their credentials
> Added login authentication

- app/controllers/posts_controller.rb
- app/controllers/sessions_controller.rb
- app/views/layouts/application.html.erb
- config/routes.rb
Added the logout route and restricted access to certain pages. Ex: Posts
> Added logout route

- features/admin_edit_moderators.feature
- features/step_definitions/social_connect_steps.rb
Wrote cucumber tests for signing in. Need to add code later for reverse chronological order
> fixed cucumber structure and wrote simple tests for logging in

- config/mongoid.yml
> Added test database

- app/models/chat_board.rb
- app/models/post.rb
- app/models/user.rb
- app/views/posts/new.html.erb
- test/controllers/users_controller_test.rb
- test/factories/user.rb
Added basic validations. Files changes were models: user.rb, post.rb, and chat_board.rb
> Added basic validations for users, posts, and chatboard

- features/step_definitions/social_connect_steps.rb
Added password_confirmation to when we create the user jack. Due to the validations I added.
> Fixed cucumber tests by adding password confirmation

- app/views/layouts/application.html.erb
- features/delete_post.feature
- features/edit_post.feature
- features/make_post.feature
- features/step_definitions/social_connect_steps.rb
- features/view_single_post.feature
Added Original Poster cucumber tests made changes to the following files: 
make_post.feature
edit_post.feature
delete_post.feature
view_single_post.feature
ssocial_connect_steps.rb
application.html.erb
Changed some of the tests to make them more basic, we can change them as we move with more features related to those features.
> Added Original Poster Cucumber Tests

- test/controllers/pages_controller_test.rb
- test/controllers/posts_controller_test.rb
- test/controllers/users_controller_test.rb
- test/factories/user.rb
- test/test_helper.rb
Fixed part of the integration test issues. 
Files changed where: 
pages_ccontroller_test.rb
posts_controller_test.rb
users_controller_test.rb
user.rb
test_helper.rb
I had to make sure in the test_helper that there was a login method so that the integration tests can access the post actions.
> Fixed part of the integration test issues

- Gemfile.lock
- app/controllers/users_controller.rb
- app/models/user.rb
I added validations in models/user.rb to ensure that passwords contain at least 1 uppercase character, lowercase character, number, and special character, as well as ensure that the length of the password string is at least 9. Tested in the app.
> Paul password

- app/controllers/posts_controller.rb
Updated posts_controller.rb to allow current_user id to be implemented into posting
> Fixed issue with updating user_id when creating post

- app/controllers/users_controller.rb
- app/views/pages/home.html.erb
- test/controllers/posts_controller_test.rb
- test/controllers/users_controller_test.rb
- test/factories/posts.rb
- test/system/posts_test.rb
- test/system/users_test.rb
- test/test_helper.rb
Updated the integrations tests and fixed a couple of capybara tests. 
Made changes to the following files:
users_controller.rb
home.html.erb
posts_controller_test.rb
users_controller_test.rb
/factories/post.rb
posts_test.rb
users_test.rb
test_helper.rb
> Updated integration tests and fixed a couple of capybara tests

- app/controllers/posts_controller.rb
- app/controllers/users_controller.rb
- app/views/posts/show.html.erb
- app/views/sessions/new.html.erb
- spec/requests/posts_spec.rb
- spec/requests/users_spec.rb
Added requests tests for both users and posts.
Added a folder named requests, and created two files: users_spec.rb and posts_spec.rb
made changes to the following files: 
posts_controller.rb
users_controller.rb
show.html.erb
new.html.erb
I made sure that some crud routes were inaccessible to users trying to access other users's post such as edit or delete.
I also made sure that flash notices and alerts appear when signing up or logging out or invalid login.
> Added request tests for users and posts

- spec/models/post_spec.rb
- spec/models/user_spec.rb
- spec/requests/posts_spec.rb
Added some basic model tests for checking to make sure validations work properly for users and posts.
Made changes to the following files: 
spec/requests/posts_spec.rb
spec/model/post_spec.rb
spec/model/user_spec.rb
All the tests successfully passed.
> Added model tests for validations of users and posts

- features/going_post.feature
- features/like_post.feature
- features/step_definitions/social_connect_steps.rb
Fixed like button cucumber test and added test for going. Added pending scenarios for unliking and unmarking going
> Paul cucumber

- app/controllers/dashboard_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/posts_controller.rb
- app/helpers/dashboard_helper.rb
- app/models/post.rb
- app/views/dashboard/moderator.html.erb
- app/views/layouts/application.html.erb
- app/views/posts/edit.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
- features/step_definitions/social_connect_steps.rb
- test/controllers/dashboard_controller_test.rb
- test/factories/posts.rb
Added functionality to moderators and also added some cucumber tests for the moderators.
Made changes to the following files:
dashboard_controller.rb
pages_controller.rb
posts_controller.rb
post.rb
moderator.html.erb
application.html.erb
routes.rb
social_connect_steps.rb
posts.rb
> 137 francisco

- app/controllers/admin/users_controller.rb
- app/controllers/posts_controller.rb
- app/helpers/admin/users_helper.rb
- app/views/admin/users/manage_moderators.html.erb
- app/views/layouts/application.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
- features/admin_edit_moderators.feature
- features/step_definitions/social_connect_steps.rb
- test/controllers/admin/users_controller_test.rb
Added functionality for admins and added some cucumber tests for admins
Made changes to the following files:
admin/users_controller.rb
admin/users/manage_moderators.html.erb
applicaton.html.erb
routes.rb
admin_edit_moderators.feature
social_connect_steps.rb
> Added admin functionality and cucumber tests for admin

- app/controllers/chat_boards_controller.rb
- test/controllers/chat_boards_controller_test.rb
- test/factories/chat_board.rb
Fixed tests that were failing for chat_board for creating and deleting.
Made changes to the following files:
chat_board.rb
chat_boards_controller.rb
chat_boards_tests_controller.rb
> Fixed tests that were failing for chat board
